src/Debb/ManagementBundle/Entity/Chassis.php
<?php

namespace Debb\ManagementBundle\Entity;

use Debb\ConfigBundle\Entity\Dimensions;
use Debb\ConfigBundle\Entity\NodeGroup;
use Debb\ManagementBundle\DataTransformer\DecimalTransformer;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Chassis
 *
 * @ORM\Table(name="chassis")
 * @ORM\Entity(repositoryClass="Debb\ManagementBundle\Repository\BaseRepository")
 */
class Chassis extends Dimensions
{
    /**
     * @var Image
     *
     * @ORM\ManyToOne(targetEntity="Debb\ManagementBundle\Entity\File", cascade={"persist"})
     */
    private $image;

    /**
     * @var integer
     *
     * @ORM\Column(name="he_size", type="integer")
     */
    private $heSize;

    /**
     * Field specification - typ
     *
     * @var \Debb\ManagementBundle\Entity\ChassisTypSpecification[]
     *
     * @ORM\OneToMany(targetEntity="Debb\ManagementBundle\Entity\ChassisTypSpecification", cascade={"persist"}, mappedBy="chassis", orphanRemoval=true)
     */
    private $typspecification;

    /**
     * @var boolean
     *
     * @ORM\Column(name="frontview", type="boolean", nullable=true)
     */
    private $frontview;

    /**
     * Node Groups
     *
     * @ORM\OneToMany(targetEntity="Debb\ConfigBundle\Entity\NodeGroup", mappedBy="draft")
     *
     * @var ArrayCollection|NodeGroup[]
     */
    private $nodeGroups;

	/**
	 * @var \Debb\ManagementBundle\Entity\File[]
	 *
	 * @ORM\ManyToMany(targetEntity="Debb\ManagementBundle\Entity\File", cascade={"all"}, orphanRemoval=true)
	 */
	private $references;

	/**
	 * @var \Debb\ManagementBundle\Entity\FlowPumpToRoom[]
	 *
	 * @ORM\OneToMany(targetEntity="Debb\ManagementBundle\Entity\FlowPumpToChassis", cascade={"persist"}, mappedBy="chassis", orphanRemoval=true)
	 */
	private $flowPumps;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->nodeGroups = new ArrayCollection();
	    $this->references = new ArrayCollection();
    }

    /**
     * Set image
     *
     * @param string $image
     *
     * @return Chassis
     */
    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set heSize
     *
     * @param integer $heSize
     *
     * @return Chassis
     */
    public function setHeSize($heSize)
    {
        $this->heSize = $heSize;

        return $this;
    }

    /**
     * Get heSize
     *
     * @return integer
     */
    public function getHeSize()
    {
        return $this->heSize;
    }

    /**
     * Set frontview
     *
     * @param boolean $frontview
     *
     * @return Chassis
     */
    public function setFrontview($frontview)
    {
        $this->frontview = $frontview;

        return $this;
    }

    /**
     * Is frontview?
     *
     * @return boolean
     */
    public function isFrontView()
    {
        return $this->frontview != null && $this->frontview == 1;
    }

    /**
     * Get frontview
     *
     * @return boolean
     */
    public function getFrontview()
    {
        return $this->frontview;
    }

    /**
     * Add nodeGroups
     *
     * @param NodeGroup $nodeGroups
     *
     * @return Chassis
     */
    public function addNodeGroup(NodeGroup $nodeGroups)
    {
        $this->nodeGroups[] = $nodeGroups;

        return $this;
    }

    /**
     * Remove nodeGroups
     *
     * @param NodeGroup $nodeGroups
     */
    public function removeNodeGroup(NodeGroup $nodeGroups)
    {
        $this->nodeGroups->removeElement($nodeGroups);
    }

    /**
     * Get nodeGroups
     *
     * @return NodeGroup[]
     */
    public function getNodeGroups()
    {
        return $this->nodeGroups;
    }

	/**
	 * Get the parents
	 *
	 * @return NodeGroup[]
	 */
	public function getParents()
	{
		return $this->getNodeGroups();
	}

    /**
     * Add typspecification
     *
     * @param \Debb\ManagementBundle\Entity\ChassisTypSpecification $typspecification
     * @return Chassis
     */
    public function addTypspecification(\Debb\ManagementBundle\Entity\ChassisTypSpecification $typspecification)
    {
	    $typspecification->setChassis($this);
        $this->typspecification[] = $typspecification;
    
        return $this;
    }

    /**
     * Set typspecification
     *
     * @param \Debb\ManagementBundle\Entity\ChassisTypSpecification[] $typspecification
     * @return Chassis
     */
    public function setTypspecification($typspecification)
    {
	    $this->typspecification = $typspecification;

	    foreach ($this->typspecification as $typspecification)
	    {
		    $typspecification->setChassis($this);
	    }

        return $this;
    }

    /**
     * Remove typspecification
     *
     * @param \Debb\ManagementBundle\Entity\ChassisTypSpecification $typspecification
     */
    public function removeTypspecification(\Debb\ManagementBundle\Entity\ChassisTypSpecification $typspecification)
    {
        $this->typspecification->removeElement($typspecification);
    }

    /**
     * Get typspecification
     *
     * @return \Debb\ManagementBundle\Entity\ChassisTypSpecification[]
     */
    public function getTypspecification($asArray = false)
    {
	    if($asArray)
	    {
		    $array = array();
		    foreach($this->getTypspecification(false) as $typSpec)
		    {
			    $array[] = $typSpec->asArray();
		    }
		    return $array;
	    }
        return $this->typspecification;
    }

	/**
	 * @inheritdoc
	 */
	public function getSizeX()
	{
		if(parent::getSizeX() < 10)
		{
			return 900;
		}
		return parent::getSizeX();
	}

	/**
	 * @inheritdoc
	 */
	public function getSizeY()
	{
		if(parent::getSizeY() < 10)
		{
			return 600;
		}
		return parent::getSizeY();
	}

	/**
	 * Add references
	 *
	 * @param \Debb\ManagementBundle\Entity\File $references
	 * @return Chassis
	 */
	public function addReference(\Debb\ManagementBundle\Entity\File $references)
	{
		$this->references[] = $references;

		return $this;
	}

	/**
	 * Remove references
	 *
	 * @param \Debb\ManagementBundle\Entity\File $references
	 */
	public function removeReference($reference)
	{
		$this->references->removeElement($reference);
	}

	/**
	 * Get references
	 *
	 * @return \Debb\ManagementBundle\Entity\File[]
	 */
	public function getReferences()
	{
		return $this->references->getValues();
	}

	/**
	 * Add flowPump
	 *
	 * @param \Debb\ManagementBundle\Entity\RackToChassis $flowPump
	 * @return Chassis
	 */
	public function addFlowPump(\Debb\ManagementBundle\Entity\FlowPumpToChassis $flowPump)
	{
		$flowPump->setChassis($this);
		$this->flowPumps[] = $flowPump;

		return $this;
	}

	/**
	 * Set flowPumps
	 *
	 * @param \Debb\ManagementBundle\Entity\FlowPumpToChassis[] $flowPumps
	 * @return Chassis
	 */
	public function setFlowPumps($flowPumps)
	{
		$this->flowPumps = $flowPumps;

		foreach ($this->flowPumps as $flowPump)
		{
			$flowPump->setChassis($this);
		}

		return $this;
	}

	/**
	 * Remove flowPump
	 *
	 * @param \Debb\ManagementBundle\Entity\RackToChassis $flowPump
	 */
	public function removeFlowPump(\Debb\ManagementBundle\Entity\FlowPumpToChassis $flowPump)
	{
		$this->flowPumps->removeElement($flowPump);
	}

	/**
	 * Get flowPumps
	 *
	 * @return \Debb\ManagementBundle\Entity\FlowPumpToChassis[]
	 */
	public function getFlowPumps()
	{
		return $this->flowPumps;
	}

	/**
	 * Sort flowPumps (unused) (reverse)
	 */
	public function sortFlowPumps()
	{
		$ordered = new \Doctrine\Common\Collections\ArrayCollection();
		for ($i = $this->flowPumps->count() - 1; $i >= 0; $i--)
		{
			$ordered->add($this->flowPumps[$i]);
		}
		$this->flowPumps = $ordered;

		$x = 0;
		foreach ($this->flowPumps as $flowPump)
		{
			$flowPump->setField($x);
			$x++;
		}
	}

	/**
	 * Get the next free field in flowPump array
	 *
	 * @return int the next free field in flowPump array
	 */
	public function getFreeFlowPump()
	{
		$ids = array();
		foreach ($this->getFlowPumps() as $flowPump)
		{
			$ids[] = $flowPump->getField();
		}
		ksort($ids);

		$res = 0;
		foreach ($ids as $id)
		{
			if ($id == $res)
			{
				$res++;
			}
		}
		return $res;
	}

	public function __clone()
	{
		if ($this->getId() > 0)
		{
			parent::__clone();

			$this->setProduct($this->getProduct() . ' - 2');

			if($this->getImage() != null)
			{
				$this->image = clone $this->image;
			}

			$references = new ArrayCollection();
			foreach($this->references as $reference)
			{
				$references->add(clone $reference);
			}
			$this->references = $references;

			$flowPumps = new ArrayCollection();
			foreach($this->flowPumps as $flowPump)
			{
				$flowPumps->add(clone $flowPump);
			}
			$this->setFlowPumps($flowPumps);

			$typSpecifications = new ArrayCollection();
			foreach($this->typspecification as $typSpecification)
			{
				$typSpecifications->add(clone $typSpecification);
			}
			$this->setTypspecification($typSpecifications);
		}
	}

	/**
	 * @return float
	 */
	public function getRealCostsEur($inclSelf = true)
	{
		$costs = 0;

		// Count flow pumps
		foreach($this->getFlowPumps() as $flowPump)
		{
			if($flowPump instanceof FlowPumpToChassis && $flowPump->getFlowPump() instanceof FlowPump)
			{
				$costs += $flowPump->getFlowPump()->getRealCostsEur();
			}
		}

		// Count self
		if($inclSelf)
		{
			$costs += parent::getRealCostsEur();
		}


src/Debb/ManagementBundle/Controller/ChassisController.php
<?php

namespace Debb\ManagementBundle\Controller;

use Debb\ConfigBundle\Controller\NodeController;
use Localdev\AdminBundle\Util\ControllerUtils;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use \Debb\ConfigBundle\Entity\Node;
use Symfony\Component\HttpFoundation\Request;

/**
 * @author Patrick Bußmann <patrick.bussmann@christmann.info>
 * @Route("/{_locale}/management/chassis", requirements={"_locale" = "en|de"}, defaults={"_locale" = "en"})
 */
class ChassisController extends BaseController
{
	/**
	 * Creates a new entity
	 *
	 * @Route("/form/{id}-{duplicated}", defaults={"id"=0, "duplicated"=0}, requirements={"id"="\d+|", "duplicated"="0|1|"});
	 * @Template()
	 *
	 * @param Request                                   $request  Request object
	 * @param int                                       $id       item id
	 *
	 * @return array
	 */
	public function formAction(Request $request, $id = 0, $duplicated = 0)
	{
		/* @var $item \Debb\ManagementBundle\Entity\Chassis */
		$GLOBALS['user_bypass'] = $this->getUser();
		$item = $this->getEntity($id);
		$flowPumps = $this->getEntities('DebbManagementBundle:FlowPump');

		$form = $this->createForm($this->getFormType($item), $item, array('attr' => array('duplicated' => $duplicated)));
		if ($request->getMethod() == 'POST')
		{
			$form->submit($request);

			if ($form->isValid())
			{
				$this->persistEntity($item);
				$this->addSuccessMsg("localdev_admin.messages.saved");
				return $this->redirect($this->generateUrl(ControllerUtils::getRouteName($this->getRequest(), '_form'), array('id' => $item->getId())));
			}
		}

		$nodeController = new NodeController();
		$nodeController->setContainer($this->getContainer());

		return $this->render($this->resolveTemplate(__METHOD__), array(
			'form' => $form->createView(),
			'item' => $item,
			'nodetypspecs' => $nodeController->getNodeTypesQuery()->execute(),
            'duplicated' => $duplicated,
			'flowPumps' => $flowPumps
		));
	}

	/**
	 * Duplicate entity
	 *
	 * @Route("/duplicate/{id}", requirements={"id"="\d+"});
	 *
	 * @param int $id item id
	 *
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function duplicateAction($id)
	{
		$item = $this->getEntity($id);
		$itemNew = clone $item;
		$this->persistEntity($itemNew);
		return $this->redirect($this->generateUrl('debb_management_chassis_form', array('id' => $itemNew->getId(), 'duplicated' => 1)));
	}
}

src/Debb/ManagementBundle/Resources/views/Chassis/form.html.twig
{% extends "DebbManagementBundle::form.html.twig" %}
{% form_theme form "DebbManagementBundle::form_theme.html.twig" %}
{% import _self as chassis %}

{% block stylesheets %}
	{{ parent() }}
	{% stylesheets filter='cssrewrite'
		'bundles/debbconfig/css/jquery-ui.min.css'
	%}
		<link href="{{ asset_url }}" type="text/css" rel="stylesheet" />
	{% endstylesheets %}
	<style>
		.node { padding: 10px; margin: 0px; }
		ul.hoz { list-style-type: none; margin: 0; padding: 0; margin-bottom: 10px; }
		li.hoz { margin: 5px; padding: 5px; width: 150px; }
	</style>
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	{% javascripts
					'@DebbConfigBundle/Resources/public/js/jquery-ui.min.js'
					'@DebbManagementBundle/Resources/public/js/chassis.js'
	%}
		<script src="{{ asset_url }}" type="text/javascript"></script>
	{% endjavascripts %}
    <script type="text/javascript">
        var chassisId = {{ form.vars.data.id | default(0) }};
    </script>
{% endblock %}

{% set chassisSizeX = form.vars.data.sizeX %}
{% set chassisSizeY = form.vars.data.sizeY %}

{% block contentExtras %} style="width: {{ chassisSizeX + 38 }}px;"{% endblock %}

{% block form %}
	{%- do form.typspecification.setRendered() -%}
	{%- do form.flowPumps.setRendered -%}
	{{- parent() -}}
	<div id="chassiscontainer" class="row-fluid" style="width: {{ chassisSizeX + 10 }}px;">
		{% if flowPumps|length > 0 -%}
			<div>
				{{ 'Add flow pump' | trans }}:
				<ul class="hoz">
					{% for flowPump in flowPumps %}
						<li class="hoz ui-state-default eDraftRack addFlowPump" style="margin-left: 0px; margin-right: 10px;"><div class="draftRack" flowPumpId="{{ flowPump.id }}" rackx="{{ flowPump.sizeY }}" racky="{{ flowPump.sizeX }}" rackz="{{ flowPump.sizeZ }}" title="{{ flowPump | e }}" inlet="{{ flowPump.inlet }}">{{ flowPump }}</div></li>
					{% endfor %}
				</ul>
			</div>
			<div class="clear"></div>
		{%- endif %}
		<div>
			<a href="#" class="addNode btn btn-small" style="border-bottom-width: 0; border-bottom-left-radius: 0; border-bottom-right-radius: 0;">{{ 'Add node' | trans }}</a>
		</div>
		<div class="clear"></div>
		<div id="chassisSize">{{ 'size' | trans }}: <span id="chassisSizeX">{{ (chassisSizeX / 1000.0) | number_format(2, '.', '') }}</span>m x <span id="chassisSizeY">{{ (chassisSizeY / 1000.0) | number_format(2, '.', '') }}</span>m</div>

		{% set spaceInfoWidth = 75 %}
		{% set itemtypspecification = item.typspecification %}
		{% if itemtypspecification | keys|default({0: -1}).0 == 0 %}
			{% set itemtypspecification = itemtypspecification | reverse %}
		{% endif %}
		<div id="nodegroupContainer" data-prototype="{{ chassis.typspec(nodetypspecs, form.typspecification.vars.prototype) | e }}" data-prototype-flowpump="{{ chassis.typspec(null, form.flowPumps.vars.prototype) | e }}" style="width: {{ chassisSizeX }}px; height: {{ chassisSizeY }}px;">
			{%- for typspec in form.typspecification -%}
				{{ chassis.typspec(nodetypspecs, typspec, true) }}
			{%- endfor -%}
			{% for flowPump in form.flowPumps %}
				{{ chassis.typspec(null, flowPump, true) }}
			{% endfor %}
		</div>
		<div class="clear"></div>
		<div id="rackScale" style="float: left; margin-left: 0px; top: -16px; width: 99px; margin-top: 6px;"><i class="icon-arrow-left"></i> {{ 'Scale' | trans }} 10cm <i class="icon-arrow-right"></i></div>
	</div>
{% endblock %}

{% macro typspec(nodetypspecs, nodeForm, nodeContainer) %}
	{% if nodeContainer is null or nodeContainer == true -%}
		<div title="{{- nodeForm.vars.data | default('') -}}" class="node node{{ nodeForm.vars.data.rotation | default(0) }}Deg" posx="{{ nodeForm.vars.data.posX|default('') }}" posy="{{ nodeForm.vars.data.posY|default('') }}" posz="{{ nodeForm.vars.data.posZ|default('') }}">
	{%- endif %}
	<a href="#" class="removeNode"><i class="icon-trash"></i></a> - <a class="rotateNode" href="#"><i class="icon-repeat" style="transform: rotateZ({{ nodeForm.vars.data.rotation | default(0) + 90 }}deg);"></i></a>
	{%- if nodetypspecs is not null %}
        <br />[<span class="nodeCount">{{ countUp('x') }}</span>]<br />
		<select name="{{ nodeForm.typ.vars.full_name }}" id="{{ nodeForm.typ.vars.id }}" style="margin-left: -7px; width: 63px; margin-top: 10px;">
			{% for value in nodetypspecs|default({}) %}
				{%- set selectedValue = nodeForm.typ.vars.data -%}
				<option value="{{ value.type }}"{% if selectedValue is defined and selectedValue is not null and selectedValue == value.type %} selected="selected"{% endif %}>{{ value.type | trans }}</option>
			{% endfor %}
		</select>
	{%- else -%}
        <br />[<span class="pumpCount">{{ countUp('y') }}</span>]<br />
		<br />
		<span class="pumpName">{{- nodeForm.vars.data | default('') -}}</span>
	{%- endif -%}
	{%- if nodeForm.typ is defined -%}{%- do nodeForm.typ.setRendered() -%}{%- endif -%}
	{{ form_widget(nodeForm) }}
	{% if nodeContainer is null or nodeContainer == true %}</div>{% endif %}
{% endmacro %}

src/Debb/ManagementBundle/Resources/views/Chassis/index.html.twig
{% extends "DebbManagementBundle::index.html.twig" %}